### ISSUE TITLE
Example does not change displayed texts

### ISSUE THREAD

**Issue by ghost** [cah4a/dart_gettext#1]
I `git clone https://github.com/cah4a/dart_gettext.git`
then open the example dir in vscode.
The app display is ok but clicking the `Change` button does nothing

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.1.10-pre.160, on Mac OS X 10.14.1 18B75, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by cah4a** [comment]
Thanks for reporting!

I found that `supportedLocales` not passed to MaterialApp widget, therefore changing locales didn't work. I've updated examples, try to pull master and recompile code. 
Should work as expected)

**Comment by ghost** [comment]
works great thanks!
